name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Added for manual triggering

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Updated to Node.js version 20

      - name: Install Dependencies
        run: npm install @octokit/rest

      - name: Update Contributors
        run: |
          const fs = require('fs');
          const { Octokit } = require('@octokit/rest');

          const octokit = new Octokit();
          const repo = github.repository;  // Using github.repository to get repository information

          try {
            const response = await octokit.repos.listContributors({
              owner: repo.owner,
              repo: repo.repo
            });

            const contributors = await Promise.all(
              response.data.slice(0, 10).map(async contributor => {
                try {
                  const user = await octokit.users.get({ username: contributor.login });
                  const avatarUrl = user.data.avatar_url;
                  return `- [${contributor.login}](${contributor.html_url}) <img src="${avatarUrl}" width="40" height="40" alt="${contributor.login}'s avatar">`;
                } catch (error) {
                  console.error(`Error fetching avatar for ${contributor.login}: ${error}`);
                  return `- [${contributor.login}](${contributor.html_url})`;  // Include only username and link
                }
              })
            );

            const readme = fs.readFileSync('README.md', 'utf8');
            const updatedReadme = readme.replace('{{ contributors }}', contributors.join('\n'));
            fs.writeFileSync('README.md', updatedReadme);
          } catch (error) {
            console.error(`Error updating contributors: ${error}`);
            process.exit(1);
          }

      - name: Add and Commit Changes
        run: git add README.md && git commit -m "Update Contributors"
