name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Added for manual triggering

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or any suitable Node.js version
      - run: npm install @octokit/rest
      - uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const { Octokit } = require('@octokit/rest');

            const octokit = new Octokit();
            const repo = context.repo;

            octokit.repos.listContributors({
              owner: repo.owner,
              repo: repo.repo
            })
            .then(response => {
              const contributors = response.data.slice(0, 10).map(async contributor => {
                try {
                  const user = await octokit.users.get({ username: contributor.login });
                  const avatarUrl = user.data.avatar_url;
                  return `- [${contributor.login}](${contributor.html_url}) <img src="${avatarUrl}" width="40" height="40" alt="${contributor.login}'s avatar">`;
                } catch (error) {
                  console.error(`Error fetching avatar for ${contributor.login}: ${error}`);
                  return `- [${contributor.login}](${contributor.html_url})`;  // Include only username and link
                }
              });

              Promise.all(contributors)
                .then(contributorList => {
                  const readme = fs.readFileSync('README.md', 'utf8');
                  const updatedReadme = readme.replace('{{ contributors }}', contributorList.join('\n'));
                  fs.writeFileSync('README.md', updatedReadme);
                })
                .catch(error => console.error(`Error updating README: ${error}`));
            })
            .catch(error => console.error(`Error fetching contributors: ${error}`));
      - uses: EndBug/add-and-commit@v7
        with:
          add: README.md
          message: Update Contributors

